maintenance:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]

documentation:
  - changed-files:
  - any-glob-to-any-file: ["**/*.md"]

feature:
  - head-branch: ["^feature", "feature"]

bug:
  - head-branch: ["^fix", "fix"]
